env:
  browser: true
  es2021: true
root: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - prettier
  - plugin:jsdoc/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
  - eslint-plugin-react-hooks
  - eslint-plugin-jsdoc
  - eslint-plugin-prettier
  - react-hooks
rules:
  no-console: error
  curly: error
  radix: error
  no-multiple-empty-lines: error
  no-new-wrappers: error
settings:
  react:
    createClass: createReactClass
    pragma: React
    fragment: Fragment
    version: detect
